# Generated by Django 4.0.4 on 2022-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_campaign',
            field=models.DateField(),
        ),
    ]
