# Generated by Django 4.0.4 on 2022-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/%y/default.png', max_length=255, null=True, upload_to='img/%y'),
        ),
    ]
